# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import subprocess
import pathlib
import threading
import os
from PyQt5 import QtWebEngineWidgets


#subprocess.run(["python", "manage.py","runserver","127.0.0.1:8000"])
class Ui_MainWindow(object):
    def setupUi(self, MainWindow,high,width):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(high, width)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webEngineView.sizePolicy().hasHeightForWidth())
        self.webEngineView.setSizePolicy(sizePolicy)
        self.webEngineView.setUrl(QtCore.QUrl("http://127.0.0.1:8000"))
        self.webEngineView.setObjectName("webEngineView")
        self.horizontalLayout.addWidget(self.webEngineView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

# class ui(threading.Thread):
#     def __init__(self):
#         threading.Thread.__init__(self)
#     def run(self):
#         subprocess.run(["python", "manage.py","runserver","127.0.0.1:8000"])

# class window(threading.Thread):
#     def __init__(self):
#         threading.Thread.__init__(self)
#     def run(self):
#         high = 800
#         width = 600
#         app = QtWidgets.QApplication(sys.argv)
#         MainWindow = QtWidgets.QMainWindow()
#         ui = Ui_MainWindow()
#         ui.setupUi(MainWindow,high,width)
#         MainWindow.show()
#         sys.exit(app.exec_())
if __name__ == "__main__":
    # thread1 = window()
    # thread1.start()
    path = os.path.abspath("./")
    subprocess.Popen("python manage.py runserver 127.0.0.1:8000", cwd = path)
    high = 800
    width = 600
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow,high,width)
    MainWindow.show()
    sys.exit(app.exec_())
    
    # thread1.join()
    
